### ISSUE TITLE
[Question] Is the Readme still correct.

### ISSUE THREAD

**Issue by ashfaqfarooqui** [svroonland/scala-ads-client#25]
I'm in the process of writing an interface from my program to TwinCat using this library. But I run into an error when subscribing to nodes. If I use the code snippet from the readme, but the following line: 
```scala
notifications.subscribe(Consumer.foreach(value => println(s"Got value ${value.value} at timestamp ${value.timestamp}"))
```
gives me an error saying subscribe is overloaded. 

Has the API changed or am I doing something wrong?

**Comment by svroonland** [comment]
Hi Ashfaq,

Nice to hear that you found this library and are using it.

Maybe the `monix` lib changed since the time I wrote the readme. The example should work if you use `consumeWith` instead of `subscribe`. You should find some guidance here too: https://monix.io/docs/3x/reactive/consumer.html

Good luck and let me know if I can be of any help or if you have any other feedback!

**Comment by ashfaqfarooqui** [comment]
Thanks!
I will try that out and provide feedback.
